import { Role, ROLES } from "../roles/system";
import { Permission, PERMISSIONS } from "./engine";

/**
 * @fileOverview Definitive mapping of roles to their allowed permissions.
 */

export const rolePermissions: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ["*"],

  [ROLES.COUNTRY_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.MANAGE_LEADS,
    PERMISSIONS.DISPATCH_WHATSAPP,
    PERMISSIONS.CREATE_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.PUBLISH_CONTENT,
    PERMISSIONS.ACCESS_SEO,
    PERMISSIONS.MANAGE_METADATA,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.CREATE_LISTING,
    PERMISSIONS.EDIT_LISTING,
    PERMISSIONS.ACCESS_AI
  ],

  [ROLES.OPERATOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.CREATE_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.ACCESS_AI
  ],

  [ROLES.VENDOR]: [
    PERMISSIONS.CREATE_LISTING,
    PERMISSIONS.EDIT_LISTING,
    PERMISSIONS.MANAGE_OWN_LISTINGS,
  ],

  [ROLES.CLIENT]: [
    PERMISSIONS.VIEW_OWN_ACTIVITY,
  ],
};
